apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kumon-marker
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/meappy/kumon-marker.git
    targetRevision: main
    path: helm/kumon-marker
    helm:
      valueFiles:
        - values.yaml
        - values-argocd.yaml
  destination:
    server: https://kubernetes.default.svc
    namespace: kumon-marker
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
